routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::put('transactions/clear/{transaction}', 'TransactionController@clearTransaction')->name('transactions.clearTransaction');
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;
use App\Item;
use App\Status;
use Auth;
use Str;
use Category;
use Illuminate\Support\Facades\DB;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Transaction $transaction)
    {
        // $categories = Category::all();
        $statuses = Status::all();
        $items = Item::all();

        if(Auth::user()->role_id === 1){
            $transactions = Transaction::all();
        }else{
            $transactions = Transaction::where('user_id', Auth::user()->id)->get();
        }
        
        // dd($items);
       
        return view('transactions.index')->with('items', $items)->with('transactions', $transactions)->with('statuses', $statuses);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       
         $request->validate([
            'borrow' => 'required',
            'return' => 'required'
        ]);


      
        // dd($request->all());
        $transaction = new Transaction;
        $transaction_number = Auth::user()->id . Str::random(8) . time();
        $user_id = Auth::user()->id;
        $borrow_date = $request->input('borrow');
        $return_date = $request->input('return');

        $transaction->transaction_number = $transaction_number;
        $transaction->user_id = $user_id;
        $item_id = $request->input('item_name');
        $transaction->item_id = $item_id;
        $transaction->borrow_date = $borrow_date;
        $transaction->return_date = $return_date;
        $transaction->save();

        $item = Item::find($item_id);
        $item->isAvailable = false;
        $item->save();
        // dd($transaction);
        // $request->session()->flash('transaction_message', 'Successfully Requested!');

        return redirect(route('transactions.show', ['transaction'=>$transaction->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction  
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        
        $items = Item::all();
        // dd($transaction->item->name);
        // echo "im here";
        return view('transactions.show')->with('transaction', $transaction)->with('items', $items);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
         
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {

        $item_id = $transaction->item_id;
        
        if($request->input('status') == 3 || $request->input('status') == 4 ) {
        // dd($request->input('status'));
            $item = Item::find($item_id);
            $item->isAvailable = true;
            $item->save();
        }

        // $transaction->status_id = $request->input('item_id');
        // dd($request->input('status'));
        $transaction->status_id = $request->input('status');

        $transaction->save();

        // echo "hey";
        return redirect(route('transactions.index'))
        ->with('updated_transaction', $transaction->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $transaction->delete();

        // echo "deleted";

        return redirect(route('items.index'))->with('destroy_message', 'Transaction Cancelled');
    }

}

resources/views/transactions/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">Pending Details</h3>
				<hr>
			</div>	
		</div>

		<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="float-right ml-3 text-warning">Status</th>
						<tbody class="table-borderless">

						@foreach($transactions as $transaction)
						{{-- {{dd($transaction)}} --}}
							@if($transaction->status->name == "pending")
				
							<tr class="text-center">
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->item->name}}</strong>
									</td>
							
									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>
									{{-- {{dd($statuses)}} --}}
									<td class="col float-right pl-5">
							
										<form action="{{ route('transactions.update', ['transaction' => $transaction->id]) }}" method="post">
				        						@csrf
				        						@method('PUT')
				        						<input type="hidden" name="item_id" value="{{$transaction->item_id}}">
				        						<select class="custom-select mb-1" id="edit-transaction-{{$transaction->id}}" name="status">
				        							@foreach($statuses as $status)
				        							<option value="{{$status->id}}" 
				        								@if($status->id == $transaction->status_id)
				        								selected 
				        								@endif 
				        								{{ $status->id == $transaction->status_id ? "selected" : ""}}
				        								>{{$status->name}}</option>
				        							@endforeach
				        						</select>
				        						@can('isAdmin')
				        						<button class="badge badge-primary">Update</button>
				        						@endcan
				        				</form>
									</td>
							@endif
						@endforeach
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center pt-5">Approved Details</h3>
				<hr>
			</div>	
		</div>

		<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="float-right ml-3 text-warning">Status</th>
						<tbody class="table-borderless">
						
						@foreach($transactions as $transaction)
						@if($transaction->status->name == 'approved')
							<tr class="text-center">
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->item->name}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>

									<td class="col float-right pl-5">
										@can('isAdmin')
										<form action="{{ route('transactions.update', ['transaction' => $transaction->id]) }}" method="post">
											@csrf
											@method('put')
											<input type="hidden" name="status" value="4">
										<button class="btn btn-info">Tag as Returned</button>
										</form>
										@endcan
										@cannot('isAdmin')
										<span class="badge badge-success">{{$transaction->status->name}}</span>
										@endcannot
									</td>
							</tr>
							@endif
						@endforeach
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>

		<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center pt-5"> Completed Transactions</h3>
				<hr>
		</div>	
	</div>

	<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="float-right ml-3 text-warning">Status</th>
						<tbody class="table-borderless">
						
						@foreach($transactions as $transaction)
						@if($transaction->status->name == 'returned')
							<tr class="text-center">
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->item->name}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>

									<td class="col float-right pl-5">
										<span class="badge badge-success">{{$transaction->status->name}}</span>
									</td>
							</tr>
							@endif
						@endforeach
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center pt-5"> Reject/Cancelled Transactions</h3>
				<hr>
		</div>	
	</div>
	<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="float-right ml-3 text-warning">Status</th>
						<tbody class="table-borderless">
						
						@foreach($transactions as $transaction)
						@if($transaction->status->name == 'reject')
							<tr class="text-center">
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->item->name}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>

									<td class="col float-right pl-5">
										@if($transaction->status->name == "cancelled")
											<button class="btn btn-warning">{{$transaction->status->name}}</button>
										@elseif($transaction->status->name == "reject")
											<span class="badge badge-danger">{{$transaction->status->name}}</span>
										@else
											<button class="badge badge-danger">{{$transaction->status->name}}</button>
										@endif
									</td>
							</tr>
							@endif
						@endforeach
						</tbody>
					</table>

				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">Request Details</h3>
				<hr>
			</div>	
		</div>

		<div class="row">
			<div class="col-12 col-md-11 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="pl-5 text-warning">Status</th>
						<th class="pl-5 text-warning">Action</th>

						<tbody class="table-borderless">
					
							<tr class="text-center">
						{{-- {{dd($transaction)}} --}}
						@foreach($items as $item)
							{{-- {{$item->name}}; --}}
						@endforeach
							@if($transaction->status->name !== "approved" && $transaction->status->name !== "reject" )
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$item->name}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>

									<td class="col float-right pl-5">
										<span class="badge badge-warning">{{$transaction->status->name}}</span>
									</td>

									<td class="col">
										<form action="{{ route('transactions.destroy', ['transaction' => $transaction->id])}}" method="post">
											{{-- {{dd($transaction->id)}} --}}
											@csrf
											@method("delete")
											<button class="btn btn-danger"><small>Cancel Transaction</small></button>
										</form>
									</td>
								@endif
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>


	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center pt-5">Approval Status</h3>
				<hr>
			</div>	
		</div>

		<div class="row">
			<div class="col-12 col-md-10 mx-auto">
				<div class="table-responsive">
					<table class="table  table-dark table-hover">
						<th class="pl-5 text-warning">Transaction Number</th>
						<th class="pl-5 text-warning">Unit Name</th>
						<th class="pl-5 text-warning">Borrow_Date</th>
						<th class="pl-5 text-warning">Return_Date</th>
						<th class="float-right mr-5 text-warning">Status</th>
						<tbody class="table-borderless">
					
							<tr class="text-center">
						{{-- {{dd($transactionss)}} --}}
						{{-- {{dd($items)}} --}}
						@if($transaction->status->name == "approved" || $transaction->status->name == "reject" )
									<td scope="col">
										<strong>{{$transaction->transaction_number}}</strong>
									</td>

									<td scope="col">
										<strong>{{$item->name}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->borrow_date}}</strong>
									</td>

									<td scope="col">
										<strong>{{$transaction->return_date}}</strong>
									</td>

									<td class="col float-right pl-5">
										@if($transaction->status->name == "pending")
											<button class="btn btn-warning">{{$transaction->status->name}}</button>
										@elseif($transaction->status->name == "reject")
											<span class="badge badge-danger">{{$transaction->status->name}}</span>
										@else
											<button class="btn btn-success">{{$transaction->status->name}}</button>
										@endif
									</td>
								@endif
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

@endsection