routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::put('transactions/clear/{transaction}', 'TransactionController@clearTransaction')->name('transactions.clearTransaction');
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('transactions', 'TransactionController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $fillable = ['name'];
    
    public function products() {
    	return $this->hasMany('App\Product');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use App\Item;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Category $category)
    {
        $items = Item::all();
        // $this->authorize('view', $category);
        $categories = Category::all();
        // dd($categories);

        return view('categories.index')->with('categories', $categories)->with('items', $items);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category)
    {
        $this->authorize('create', $category);
        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category)
    {
        $this->authorize('create', $category);
         //validation for categories 
        $request->validate([
            'category' => 'required|string|unique:categories,name'
        ]);

        // this will store in database
        Category::create([
            'name' => $request->input('category')
        ]);

        // for error handling
        $request->session()->flash('category_message', 'Category Successfully Added!');

        return redirect(route('categories.create'));


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        $this->authorize('view', $category);

        return view('category.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $this->authorize('update', $category);
        return view('categories.create')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $this->authorize('update', $category);
         
        $request->validate([
            'category' => 'required|string|unique:categories,name'
        ]);

        $category->update([
            'name' => $request->input('category')
        ]);

        $request->session()->flash('category_message', 'Category Successfully Updated!');

        return redirect(route('categories.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $this->authorize('delete', $category);
        $category->delete();

        return redirect(route('categories.index'))->with('destroy_message', 'Product Deleted');

    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container shadow p-5">
		<div class=row>
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					{{isset($category) ? 'Edit Category' : 'Create Category'}}
				</h3>
				<hr>
				<form action="{{isset($category) ? route('categories.update', ['category'=>$category->id]) : route('categories.store')}}" method="post">
					@csrf
					@if(isset($category))
					@method('put')
					@endif
				@if(Session::has('category_message'))
					<div class="alert alert-success">
						{{Session::get('category_message')}}
					</div>
				@endif
				@if($errors->has('category'))
					<div class="alert alert-danger">
						<small class="mb-0">Category Required</small>
					</div>
				@endif
					<div class="form-group text-center">
						<label for="category" >New Category</label>
							<input type="text" name="category" class="form-control" 
								value="{{isset($category) ? $category->name : "" 	}}"
							>
					</div>
						<button  class="btn btn-info w-100">{{isset($category) ? "Update" : "Add"}}</button>
				</form>
			</div>	
		</div>
		
	</div>

@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				{{-- update/add category alert --}}
				@if(Session::has('category_message'))
				<div class="alert alert-success">
					{{Session::get('category_message')}}
				</div>
				@endif
				{{-- delete alert --}}
				@if(Session::has('destroy_message'))
				<div class="alert alert-success">
					{{Session::get('destroy_message')}}
				</div>
				@endif

				<h2 class="text-center titleCategory display-4">Categories</h2>
				{{-- Start of table --}}
				<table class="table  table-dark table-hover">
					<th class="pl-5 text-warning">Categories</th>
					@can('isAdmin')
					<th class="float-right ml-5 text-warning">Action</th>
					@endcan
					<tbody class="table-borderless">
						{{-- @foreach($items as $item) --}}
						@foreach($categories as $category)
							<tr>
								{{-- @if($item->category_id == $category->id) --}}
						{{-- {{dd($item->category_id == $category->id)}} --}}
								<td scope="col">
									<strong class="float-left">{{$category->name}}</strong>
								</td>
								<td class="float-right">
									@can('isAdmin')
									<a href="{{route('categories.edit', ['category'=> $category->id])}}" class="btn btn-primary"><small>Edit</small></a>
								</td>

								<td>
									<form action="{{route('categories.destroy', ['category'=> $category->id])}}" method="post">
										@csrf
										@method("delete")
										<button class="btn btn-danger"><small>Delete</small></button>
									</form>
									@endcan
								</td>
								{{-- @endif --}}	
							</tr>
						{{-- @endforeach --}}
						@endforeach
					</tbody>
				</table>
			</div>	
		</div>
	</div>

@endsection