routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::put('transactions/clear/{transaction}', 'TransactionController@clearTransaction')->name('transactions.clearTransaction');
Route::get('/home', 'HomeController@index')->name('home');


Route::resource('categories', 'CategoryController');
Route::resource('items', 'ItemController');
Route::resource('transactions', 'TransactionController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use SoftDeletes;

    public function category() {
    	return $this->belongsTo('App\Category');
    }

    public function transaction() {
    	return $this->hasMany('App\Transaction');
    }

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;
use App\Category;
use Str;
use DB;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = Category::all();

        // dd($request->query('category')); filter category
        if($request->query('category')){
            $items = Item::all()->where('category_id', $request->query('category'));
        }else {
            $items = Item::all();
        }

        return view('items.index')->with('items', $items)->with('categories', $categories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Item $item)
    {
        $this->authorize('create', $item);
        $categories = Category::all();
        return view('items.create')->with('categories', $categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Item $item)
    {
        $this->authorize('create', $item);
        $request->validate([
            'name' => 'required|string',
            'category' => 'required',
            'image' => 'required|image|max:20000',
            'description' => 'required|string',
        ]);

        $file = $request->file('image');

        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

            // 2.3 get uploaded file extension name
            $file_extension = $file->extension();

            // 2.4 generate new name with random characters 
            $random_chars = Str::random(10);

            $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

            // dd($new_file_name);

             // 2.5 save the new file to public folder
            $filepath = $file->storeAs('images', $new_file_name,'public');

            //== // 3. get input values from form
            $name = $request->input('name');
            $price = $request->input('price');
            $category_id = $request->input('category');
            $description = $request->input('description');
            $image = $filepath;

            //== // 4. save the details to the database
            $item = new Item;
            $item->name = $name;
            $item->category_id = $category_id;
            $item->description = $description;
            $item->image = $image;

            $item->save();

        $request->session()->flash('item_message', 'Unit Successfully Added!');

          //== // 5. redirect user to view the newly created product
        return redirect(route('items.show', ['item'=> $item->id]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show(Item $item)
    {
        return view('items.show')->with('items', $item);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        $this->authorize('update', $item);
        $categories = Category::all();
        return view('items.edit')->with('item', $item)->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $this->authorize('update', $item);
        $request->validate([
            'name' => 'required|string',
            'category' => 'required',
            'description' => 'required|string',
        ]);

       if(
            !$request->hasFile('image') &&
            $item->name == $request->input('name') &&
            $item->description == $request->input('description') &&
            $item->category_id == $request->input('category') 

        ){
            $request->session()->flash('update_failed', 'No changes made');
            
        }else {
            // update the entry in the database and return the updated entry

            // check if there's a file uploaded
            if($request->hasFile('image')){
                $request->validate([
                    'image' => 'required|image|max:20000'
                ]);

                $file = $request->file('image');
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                $file_extension = $file->extension();
                $random_chars = Str::random(10);
                $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." . $file_extension;

                $filepath = $file->storeAs('images', $new_file_name,'public');

                // set the new image path as image value of product
                $item->image = $filepath;
            }


             //  update attributes
            $item->name = $request->input('name');
            $item->category_id = $request->input('category');
            $item->description = $request->input('description');

            $item->save();

        $request->session()->flash('update_success', 'Item Successfully Updated!');

          // redirect user to view the newly created product
        return redirect(route('items.show', ['item'=> $item->id]));
    }

}

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $this->authorize('delete', $item);
        $item->delete();

        return redirect(route('items.index'))->with('destroy_message', 'Unit Deleted');
    }

}

resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="jumbotron text-center display-4">{{isset($item) ? 'Edit Asset' : 'Create New Asset'}}</h3>
				<hr>
				<form method="post" action="{{ route('items.store') }}" enctype="multipart/form-data">
					@csrf
					@if(isset($item))
					@method('put')
					@endif
				@if(Session::has('item_message'))
				<div class="alert alert-success">
					{{Session::get('item_message')}}
				</div>
				@endif
					{{-- input for Unit name --}}
					<div class="form-group">
						<h4>Asset Name:</h4>
						<input type="text" name="name" class="form-control" id="name">
					</div>
					@if($errors->has('name'))
						<div class="alert alert-danger">
							<small class="mb-0">Asset name Required</small>
						</div>
					@endif

					{{-- input for Category --}}
					<div class="form-group">
						<h4>Category:</h4>
						<select class="form-control" id="category" name="category">
							@foreach($categories as $category)
								<option value="{{$category->id}}">{{$category->name}}</option>
							@endforeach
						</select>
					</div>

					{{-- input for image --}}
					<div class="form-group">
						<label class="image">Asset Image:</label>
						<input type="file" name="image" class="form-control-file" id="image">
					</div>
					@if($errors->has('image'))
						<div class="alert alert-danger">
							<small class="mb-0">Product image Required</small>
						</div>
					@endif

					{{-- input for description --}}
					<div class="form-group">
						<h4>Description:</h4>
						<textarea id="description" name="description" class="form-control" id="description" cols="30" rows="10"></textarea>
					</div>
					@if($errors->has('description'))
						<div class="alert alert-danger">
							<small class="mb-0">Product description Required</small>
						</div>
					@endif

					<button class="btn btn-primary btn-block">Add Asset</button>
				</form>
			</div>
		</div>
	</div>


@endsection

resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					Edit Asset 
				</h3>
				<hr>
				<form method="POST" action="{{ route('items.update', ['item' => $item->id]) }}" enctype="multipart/form-data">
					@csrf
					@method('PUT')
					{{-- input for name --}}
					<div class="form-group">
						<label for="name">Product name:</label>
						<input 
							type="text" 
							name="name" 
							class="form-control" 
							id="name" 
							value="{{$item->name}}">
					</div>
					@if($errors->has('name'))
						<div class="alert alert-danger">
							<small class="mb-0">Product name Required</small>
						</div>
					@endif

					{{-- input for category --}}
					 <div class="form-group">
					    <label for="category">Product Category</label>
					    <select 
					    	class="form-control" 
					    	id="category" 
					    	name="category">
					      @foreach($categories as $category)
					     	 <option 
					     	 	value="{{$category->id}}" 
					     	 	@if($item->category_id == $category->id)selected @endif>{{$category->name}}
					     	 </option>
					      @endforeach

					      </select>
					 </div>

					{{-- input for image --}}
					<div class="form-group">
						<label for="image">Product image:</label>
						<input 
							type="file" 
							name="image" 
							class="form-control-file" 
							id="image">
					</div>
					@if($errors->has('image'))
						<div class="alert alert-danger">
							<small class="mb-0">Product image Required. Check if image is not greater than 2mb</small>
						</div>
					@endif

					{{-- input for description --}}
					<div class="form-group">
						<label for="description">Product description:</label>
						<textarea id="description" name="description" class="form-control" id="description" cols="30" rows="10">{{$item->description}}</textarea>
					</div>
					@if($errors->has('description'))
						<div class="alert alert-danger">
							<small class="mb-0">Product description Required</small>
						</div>
					@endif

					<button class="btn btn-primary btn-block">Update</button>

				</form>
			</div>
		</div>
	</div>

@endsection

resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
 
	@if(Session::has('destroy_message'))
		<div class="alert alert-success">
			{{ Session::get('destroy_message') }}
		</div>
	@endif
	
	<div class="container shadow">
		<div class="row">
			<div class="col-12">
				<div class="jumbotron">
					<h1 class="text-center h1">Looking for a Ride?</h1>
				</div>
			</div>
		</div>

		{{-- filter Categories --}}
		<form action="{{route('items.index')}}" method="get">
			@csrf
			<label for="category">Filter by Categories:</label>
			<select class="custom-select mb-1 w-50" id="category" name="category">
				@foreach($categories as $category	)
				<option value="{{$category->id}}" 
				@foreach($items as $item)
					@if($category->id == $item->category_id)
				       selected 
				    @endif 
				@endforeach
					>{{$category->name}}</option>
				@endforeach
			</select>
			<button class="btn btn-primary"><small>Apply</small></button>
		</form>

		<div class="row">
			{{-- <div class="col-12 col-md-8"> --}}
				{{-- {{dd($items)}} --}}
				@foreach($items as $item)
					<div class="col-12 col-md-6 mb-5">
						<div class="card w-100 h-100 shadow-lg p-3 bg-white rounded">
							<img src="{{ url('/public/'. $item->image) }}" class="card-img-top imgIndex">
							@if($item->isAvailable == 1)
								<h6><span class="badge badge-success mt-2 float-right">{{$item->isAvailable ? 'Available' : 'Not available' }}</span></h6>
							@else
								<h6><span class="badge badge-danger mt-2 float-right">{{$item->isAvailable ? 'Available' : 'Not available' }}</span></h6>
							@endif

							{{-- <h6 class="mt-2"><span class="badge badge-success float-right"></span></h6> --}}
							
							<div class="card-body">
								<div class="pb-3">
									<h4 class="card-title text-primary prod">{{$item->name}}</h4>
								</div>
									<p class="card-text mt-2 des">{{$item->description}}</p>  
							</div>
							<div class="card-foot">
								
								{{-- view button --}}
								<a href="{{route('items.show', ['item'=> $item->id])}}" class="btn btn-primary w-100 ">View</a>

								{{-- edit item --}}
								@can('isAdmin')
								<a href="{{route('items.edit', ['item'=> $item->id])}}" class="btn btn-warning w-100 my-1">Edit item</a>

								{{-- delete form --}}
								<form action="{{route('items.destroy', ['item' => $item->id])}}" method="post">
									@csrf
									@method('DELETE')
									<button class="btn btn-danger w-100">Delete Unit</button>
								</form>
								@endcan
								
							</div>
						</div>
					</div>
				@endforeach
			{{-- </div> --}}
		</div>
	</div>

@endsection

resources/views/items/show.blade.php
@extends('layouts.app')

@section('content')
{{-- {{dd($items)}} --}} 

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-6 mx-auto">
				<h3 class="text-center">
					View Units
				</h3>
				<hr>
				<div class="card">
					<img src="{{ url('/public/'. $items->image) }}" class="card-img-top view">
					
					<form action="{{route('transactions.store')}}" method="post">
					<div class="card-body">
							<h5><span class="badge badge-success float-right">{{$items->isAvailable ? 'Available' : 'Not available'}}</span></h5>
							<input type="hidden" name="item_name" value="{{$items->id}}">
							<h2 class="card-title">{{$items->name}}</h2>
							<span class="text-primary font-weight-bold">Model Details:</span>
							<p class="card-text">{{$items->description}}</p>
					</div>
					<div class="input-group mb-3">
							<div class="form-group w-100">
								@csrf
								@if(Session::has('transaction_message'))
								<div class="alert alert-success">
									{{Session::get('transaction_message')}}
								</div>
								@endif

								<input type="hidden" name="request" value="{{$items->id}}">
								<label for="request_date"></label>
								{{-- calendar --}}
								<div class="form-group">
								    <p class="ml-2 text-info">Borrow Date:</p>
								    <input type="date" name="borrow" id="borrow" class="form-control"/>
								 </div>

								 @if($errors->has('borrow'))
								 	<div class="alert alert-danger">
								 		<small class="mb-0">Date Required</small>
								 	</div>
								 @endif

								<div class="form-group">
								    <p class="ml-2 text-info">Return Date:</p>
								    <input type="date" name="return" id="return" class="form-control"/>
								</div>
								
							 @if($errors->has('return'))
								 <div class="alert alert-danger">
								 	<small class="mb-0">Date Required</small>
								 </div>
							 @endif
							</div> {{-- end of calendar --}}
							
							 @cannot('isAdmin')
							 @if($items->isAvailable)
								<button type="submit" class="btn btn-success mt-5 w-100">Rent</button>
							 @endif
							 @endcannot
						</form>

						@can('isAdmin')
						<a href="{{route('items.edit', ['item'=> $items->id])}}" class="btn btn-warning w-100 my-1">Edit Products</a>

						<form action="{{route('items.destroy', ['item'=> $items->id])}}" method="post" class="w-100">
							@csrf
							@method('DELETE')
							<button class="btn btn-danger btn-block">Delete Product</button>
						</form>
						@endcan 
						
					</div>
						
				</div>
			</div>
		</div>
	</div>

@endsection